name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "18.x"
  OS_IMAGE: "ubuntu-latest"
jobs:
  install-dependencies:
    runs-on: $OS_IMAGE
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm run ci

      - name: Cache Node Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

  unit-test:
    runs-on: $OS_IMAGE
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3

      - name: Get Cached Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION

      - name: Run Unit Tests
        run: npm run test:unit

  component-test:
    runs-on: $OS_IMAGE
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Cached Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION

      - name: Run Component Tests
        run: npm run test:component:headless

  e2e:
    runs-on: $OS_IMAGE
    needs: install-dependencies
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Cached Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION

      - name: Synchronize Test Database
        run: npm run db:sync
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        with:
          build: npm run build
          start: npm start
